export default function Municipi(departamento) {
  switch (departamento) {
    case "Amazonas":
      const Amazonas = [
        {
          label: "Leticia",
          value: "leticia",
        },
        {
          label: "puerto nariño",
          value: "puerto nariño",
        },
      ];
      return Amazonas;
      break;

    case "Antioquia":
      const Antioquia = [
        { label: "Medellín", value: "Medellín" },
        { label: "Abejorral", value: "Abejorral" },
        { label: "Abriaqui", value: "Abriaqui" },
        { label: "Alejandria", value: "Alejandria" },
        { label: "Amaga", value: "Amaga" },
        { label: "Amalfi", value: "Amalfi" },
        { label: "Andes", value: "Andes" },
        { label: "Angelopus", value: "Angelopus" },
        { label: "Angostura", value: "Angostura" },
        { label: "Anori", value: "Anori" },
        { label: "Santafe de Antioquia", value: "Santafe de Antioquia" },
        { label: "Anza", value: "Anza" },
        { label: "Apartado", value: "Apartado" },
        { label: "Arboletes", value: "Arboletes" },
        { label: "Argelia", value: "Argelia" },
        { label: "Armenia", value: "Armenia" },
        { label: "Barbosa", value: "Barbosa" },
        { label: "Belmira", value: "Belmira" },
        { label: "Bello", value: "Bello" },
        { label: "Betania", value: "Betania" },
        { label: "Betulia", value: "Betulia" },
        { label: "Ciudad Bolivar", value: "Ciudad Bolivar" },
        { label: "Briceño", value: "Briceño" },
        { label: "Buritica", value: "Buritica" },
        { label: "Caceres", value: "Caceres" },
        { label: "Caicedo", value: "Caicedo" },
        { label: "Caldas", value: "Caldas" },
        { label: "Campamento", value: "Campamento" },
        { label: "Cañasgordas", value: "Cañasgordas" },
        { label: "Caracoli", value: "Caracoli" },
        { label: "Caramanta", value: "Caramanta" },
        { label: "Carepa", value: "Carepa" },
        { label: "Carmen Viboral", value: "Carmen Viboral" },
        { label: "Carolina", value: "Carolina" },
        { label: "Caucasia", value: "Caucasia" },
        { label: "Chigorodo", value: "Chigorodo" },
        { label: "Cisneros", value: "Cisneros" },
        { label: "Concordia", value: "Concordia" },
        { label: "Copacabana", value: "Copacabana" },
        { label: "Dabeiba", value: "Dabeiba" },
        { label: "Don Matias", value: "Apartadó" },
        { label: "Ebejico", value: "Ebejico" },
        { label: "El Bagre", value: "El Bagre" },
        { label: "Entrerrios", value: "Entrerrios" },
        { label: "Envigado", value: "Envigado" },
        { label: "Fredonia", value: "Fredonia" },
        { label: "Frontino", value: "Frontino" },
        { label: "Giraldo", value: "Giraldo" },
        { label: "Giraldota", value: "Giraldota" },
        { label: "Gomez Plata", value: "Gomez Plata" },
        { label: "Granada", value: "Granada" },
        { label: "Guadalupe", value: "Guadalupe" },
        { label: "Guarne", value: "Guarne" },
        { label: "Guatape", value: "Guatape" },
        { label: "Heliconia", value: "Heliconia" },
        { label: "Itagui", value: "Itagui" },
        { label: "Ituango", value: "Ituango" },
        { label: "Jardin", value: "Jardin" },
        { label: "Jerico", value: "Jerico" },
        { label: "La ceja", value: "La ceja" },
        { label: "La estrella", value: "La estrella" },
        { label: "La pintada", value: "La pintada" },
        { label: "La Union", value: "La Union" },

        { label: "Liborina", value: "Liborina" },
        { label: "Maceo", value: "Maceo" },
        { label: "Marinilla", value: "Marinilla" },
        { label: "Montebello", value: "Montebello" },
        { label: "Murindo", value: "Murindo" },
        { label: "Mutata", value: "Mutata" },
        { label: "Nariño", value: "Nariño" },
        { label: "Necocli", value: "Necocli" },
        { label: "Nechi", value: "Nechi" },
        { label: "Olaya", value: "Olaya" },
        { label: "Peñol", value: "Peñol" },
        { label: "Peque", value: "Peque" },
        { label: "Pueblirico", value: "Pueblirico" },
        { label: "Puerto Berrio", value: "Puerto Berrio" },
        { label: "Puerto Nare", value: "Puerto Nare" },
        { label: "Puerto Triunfo", value: "Puerto Triunfo" },
        { label: "Remedio", value: "Remedio" },
        { label: "Retiro", value: "Retiro" },
        { label: "RioNegro", value: "RioNegro" },
        { label: "Sabanalarga", value: "Sabanalarga" },
        { label: "Sabaneta", value: "Sabaneta" },
        { label: "Salgar", value: "Salgar" },
        { label: "San Andres", value: "San Andres" },
        { label: "San Carlos", value: "San Carlos" },
        { label: "San Francisco", value: "San Francisco" },
        { label: "San Jeronimo", value: "San Jeronimo" },

        { label: "San Jose de la Montaña", value: "San Jose de la Montaña" },
        { label: "Sanjuan de Uraba", value: "Sanjuan de Uraba" },
        { label: "San Luis", value: "San Luis" },
        { label: "San Pedro", value: "San Pedro" },
        { label: "San Pedro de Uraba", value: "San Pedro de Uraba" },
        { label: "San Rafael", value: "San Rafael" },
        { label: "San Roque", value: "San Roque" },
        { label: "San Vicente", value: "San Vicente" },
        { label: "Santa Barbara", value: "Santa Barbara" },
        { label: "Santa Rosa de Osos", value: "Santa Rosa de Osos" },
        { label: "Santo Domingo", value: "Santo Domingo" },
        { label: "Santuario", value: "Santuario" },
        { label: "Segovia", value: "Segovia" },
        { label: "Sonson", value: "Sonson" },

        { label: "Sopetran", value: "Sopetran" },
        { label: "Tamesis", value: "Tamesis" },
        { label: "Taraza", value: "Taraza" },
        { label: "Tarso", value: "Tarso" },
        { label: "Titiribi", value: "Titiribi" },
        { label: "Toledo", value: "Toledo" },
        { label: "Turbo", value: "Turbo" },
        { label: "Uramita", value: "Uramita" },
        { label: "Urrao", value: "Urrao" },
        { label: "Valdivia", value: "Valdivia" },
        { label: "Valparaiso", value: "Valparaiso" },
        { label: "Vegachi", value: "Vegachi" },
        { label: "Venecia", value: "Venecia" },
        { label: "Vigia del Fuerte", value: "Vigia del Fuerte" },
        { label: "Yali", value: "Yali" },
        { label: "Yarumal", value: "Yarumal" },
        { label: "Yolombo", value: "Yolombo" },
        { label: "Yomdo", value: "Yomdo" },
        { label: "Zaragoza", value: "Zaragoza" },
      ];
      return Antioquia;
      break;

    case "Arauca":
      const Arauca = [
        { label: "Arauca", value: "Arauca" },
        { label: "Arauquita", value: "Arauquita" },
        { label: "Cravo Norte", value: "Cravo Norte" },
        { label: "Fortul", value: "Fortul" },
        { label: "Puerto Rondon", value: "Puerto Rondon" },
        { label: "Saravena", value: "Saravena" },
        { label: "Tame", value: "Tame" },
      ];
      return Arauca;
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      c;
      break;

    case "Atlantico":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Atlantico = [
        { label: "Barranquilla", value: "Barranquilla" },
        { label: "Baranoa", value: "Baranoa" },
        { label: "Campo de la Cruz", value: "Campo de la Cruz" },
        { label: "Candelaria", value: "Candelaria" },
        { label: "Galapa", value: "Galapa" },
        { label: "Juan de Acosta", value: "Juan de Acosta" },
        { label: "Luruaco", value: "Luruaco" },
        { label: "Malambo", value: "Malambo" },
        { label: "Manati", value: "Arauquita" },
        { label: "Palmar de Valera", value: "Cravo Norte" },
        { label: "Piojo", value: "Fortul" },
        { label: "Polonuevo", value: "Polonuevo" },
        { label: "Ponedera", value: "Ponedera" },
        { label: "Puerto Colombia", value: "Puerto Colombia" },
        { label: "Repelon", value: "Repelon" },
        { label: "Sabanagrande", value: "Sabanagrande" },
        { label: "Sabana Larga", value: "Sabana Larga" },
        { label: "Santa lucia", value: "Santa lucia" },
        { label: "Santo Tomas", value: "Santo Tomas" },
        { label: "Soledad", value: "Soledad" },
        { label: "Suan", value: "Suan" },
        { label: "Tubara", value: "Tubara" },
        { label: "Usiacuri", value: "Usiacuri" },
      ];
      return Atlantico;
      break;

    case "Bogota":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Bogota = [
        { label: "Bogota Dc", value: "Bogotad Dc" },
        { label: "Soacha", value: "Soacha" },
        { label: "Facatativa", value: "Facatativa" },
        { label: "Chia", value: "Chia" },
        { label: "Zipaquira", value: "Zipaquira" },
        { label: "Mosquera", value: "Mosquera" },
        { label: "Madrid", value: "Madrid" },
        { label: "Funza", value: "Funza " },
        { label: "Cajica", value: "Cajica" },
        { label: "Sibate", value: "Sibate" },
        { label: "Tocancipa", value: "Tocancipa" },
        { label: "Tabio", value: "Tabio" },
        { label: "Sopo", value: "Sopo" },
        { label: "La Calera", value: "La Calera" },
        { label: "Cota", value: "Cota" },
        { label: "Tenjo", value: "Tenjo" },
        { label: "El Rosal", value: "El Rosal" },
        { label: "Gachancipa", value: "Gachancipa" },
        { label: "Bojaca", value: "Bojaca" },
      ];
      return Bogota;
      break;

    case "Bolivar":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Bolivar = [
        { label: "Achi", value: "Achi" },
        { label: "Altos del Rosario", value: "Altos del Rosario" },
        { label: "Arenal", value: "Arenal" },
        { label: "Arjona", value: "Arjona" },
        { label: "Arroyohondo", value: "Arroyohondo" },
        { label: "Barranco de loba", value: "Barranco de loba" },
        { label: "Calamar", value: "Calamar" },
        { label: "Cantagallo", value: "Cantagallo" },
        { label: "El Carmen De Bolivar", value: "El Carmen De Bolivar" },
        { label: "Cartagena de Indias", value: "Cartagena de Indias" },
        { label: "Cicuco", value: "Cicuco" },
        { label: "Clemencia", value: "Clemencia" },
        { label: "Cordoba", value: "Cordoba" },
        { label: "El Guamo", value: "El Guamo" },
        { label: "El Peñoñ", value: "El Peñoñ" },
        { label: "Hatillo de Loba", value: "Hatillo de Loba" },
        { label: "Magangue", value: "Magangue" },
        { label: "Mahates", value: "Mahates" },
        { label: "Margarita", value: "Margarita" },

        { label: "Maria la baja", value: "Maria la baja" },
        { label: "Monte Cristo", value: "Monte Cristo" },
        { label: "Morales", value: "Morales" },
        { label: "Norosi", value: "Norosi" },
        { label: "Pinillos", value: "Pinillos" },
        { label: "Regidor", value: "Regidor" },
        { label: "Rio Viejo", value: "Rio Viejo" },
        { label: "San Cristobal", value: "San Cristobal" },
        { label: "San Estanislao", value: "San Estanislao" },
        { label: "San Fernando", value: "San Fernando" },
        { label: "San Jacinto", value: "San Jacinto" },
        { label: "San Jacinto del Cauca", value: "San Jacinto del Cauca" },
        { label: "San Juan Nepomuceno", value: "San Juan Nepomuceno" },
        { label: "San Martin de Loba", value: "San Martin de Loba" },
        { label: "San Pablo", value: "San Pablo" },
        { label: "Santa Catalina", value: "Santa Catalina" },
        { label: "Santa Cruz de Mompox", value: "Santa Cruz de Mompox" },
        { label: "Santa Rosa", value: "Santa Rosa" },
        { label: "Santa Rosa del Sur", value: "Santa Rosa del Sur" },

        { label: "Samiti", value: "Samiti" },
        { label: "Soplaviento", value: "Soplaviento" },
        { label: "Talaiguanuevo", value: "Talaiguanuevo" },
        { label: "Tiquisio", value: "Tiquisio" },
        { label: "Turbaco", value: "Turbaco" },
        { label: "Turbana", value: "Turbana" },
        { label: "Villanueva", value: "Villanueva" },
        { label: "Zamrabo", value: "Zamrabo" },
      ];
      return Bolivar;
      break;

    case "Boyaca":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Boyaca = [
        { label: "Tunja", value: "Tunja" },
        { label: "Almedia", value: "Almedia" },
        { label: "Quitania", value: "Quitania" },
        { label: "Arcabuco", value: "Arcabuco" },
        { label: "Belen", value: "Belen" },
        { label: "Bermeo", value: "Bermeo" },
        { label: "Betetitiva", value: "Betetitiva" },
        { label: "Boavita", value: "Boavita" },
        { label: "Boyaca", value: "Boyaca" },
        { label: "Briceño", value: "Briceño" },
        { label: "Buenovista", value: "Buenovista" },
        { label: "Busbanza", value: "Busbanza" },
        { label: "Caldas", value: "Caldas" },
        { label: "Campohermoso", value: "Campohermoso" },
        { label: "Cerinza", value: "Cerinza" },
        { label: "Chinavita", value: "Chinavita" },
        { label: "Chiquinquira", value: "Chiquinquira" },
        { label: "Chiquiza", value: "Chiquiza" },
        { label: "Chiscas", value: "Chiscas" },

        { label: "Chita", value: "Chita" },
        { label: "Chitaraque", value: "Chitaraque" },
        { label: "Chivata", value: "Chivata" },
        { label: "Chivor", value: "Chivor" },
        { label: "Cienaga", value: "Cienaga" },
        { label: "Combita", value: "Combita" },
        { label: "Coper", value: "Coper" },
        { label: "Corrales", value: "Corrales" },
        { label: "Covarachia", value: "Covarachia" },
        { label: "Curaba", value: "Curaba" },
        { label: "Cucaita", value: "Cucaita" },
        { label: "Cuitiva", value: "Cuitiva" },
        { label: "Duitama", value: "Duitama" },
        { label: "El cocuy", value: "El cocuy" },
        { label: "El Espinoso", value: "El Espinoso" },
        { label: "Firavitoba", value: "Firavitoba" },
        { label: "Floresta", value: "Floresta" },
        { label: "Guachantiva", value: "Guachantiva" },
        { label: "Gameza", value: "Gameza" },

        { label: "Garagoa", value: "Garagoa" },
        { label: "Guacamayas", value: "Guacamayas" },
        { label: "Guateque", value: "Guateque" },
        { label: "Guayata", value: "Guayata" },
        { label: "Guican", value: "Guican" },
        { label: "Iza", value: "Iza" },
        { label: "Jenesano", value: "Jenesano" },
        { label: "Jerico", value: "Jerico" },

        { label: "La Capilla", value: "La Capilla" },
        { label: "La Uvita", value: "La Uvita" },
        { label: "La Victoria", value: "La Victoria" },
        { label: "Labranzagrande", value: "Labranzagrande" },
        { label: "Macanal", value: "Macanal" },
        { label: "Maripi", value: "Maripi" },
        { label: "Miraflores", value: "Miraflores" },
        { label: "Mongua", value: "Mongua" },

        { label: "Mongui", value: "Mongui" },
        { label: "Moniquira", value: "Moniquira" },
        { label: "Motavita", value: "Motavita" },
        { label: "Muzo", value: "Muzo" },
        { label: "Nobsa", value: "Nobsa" },
        { label: "Nuevo Colon", value: "Nuevo Colon" },
        { label: "Oicata", value: "Oicata" },
        { label: "Otanche", value: "Otanche" },

        { label: "Pachavita", value: "Pachavita" },
        { label: "Paez", value: "Paez" },
        { label: "Paipa", value: "Paipa" },
        { label: "Pajarito", value: "Pajarito" },
        { label: "Panqueba", value: "Panqueba" },
        { label: "Pauna", value: "Pauna" },
        { label: "Paya", value: "Paya" },
        { label: "Paz de Rio", value: "Paz de Rio" },

        { label: "Pesca", value: "Pesca" },
        { label: "Pisboa", value: "Pisboa" },
        { label: "Puerto Boyaca", value: "Puerto Boyaca" },
        { label: "Quimpama", value: "Quimpama" },
        { label: "Ramiriqui", value: "Ramiriqui" },
        { label: "Raquira", value: "Raquira" },
        { label: "Rondon", value: "Rondon" },
        { label: "Saboya", value: "Saboya" },

        { label: "Sachira", value: "Sachira" },
        { label: "Samaca", value: "Samaca" },
        { label: "San Eduando", value: "San Eduando" },
        { label: "San jose de pare", value: "San jose de pare" },
        { label: "San luis de Gaceno", value: "San luis de Gaceno" },
        { label: "San Mateo", value: "San Mateo" },
        { label: "San Pablo de Borbur", value: "San Pablo de Borbur" },
        { label: "Santa Maria", value: "Santa Maria" },
        { label: "Santa rosa de viterbo", value: "Santa rosa de viterbo" },
        { label: "Sanra Sofia", value: "Sanra Sofia" },
        { label: "Santana", value: "Santana" },
        { label: "Sativamprte", value: "Sativamprte" },
        { label: "Sitavasur", value: "Sitavasur" },
        { label: "Siachoque", value: "Siachoque" },
        { label: "Soata", value: "Soata" },
        { label: "Socha", value: "Socha" },

        { label: "Socota", value: "Socota" },
        { label: "Sogamoso", value: "Sogamoso" },
        { label: "Somondoco", value: "Somondoco" },
        { label: "Sora", value: "Sora" },
        { label: "Soraca", value: "Soraca" },
        { label: "Sotaquira", value: "Sotaquira" },
        { label: "Susacon", value: "Susacon" },
        { label: "Sutamarchan", value: "Sutamarchan" },
        { label: "Sutatenza", value: "Sutatenza" },
        { label: "Tasco", value: "Tasco" },
        { label: "Tensa", value: "Tensa" },
        { label: "Tibana", value: "Tibana" },
        { label: "Tibasosa", value: "Tibasosa" },
        { label: "Tinjaca", value: "Tinjaca" },
        { label: "Tipacoque", value: "Tipacoque" },
        { label: "Toca", value: "Toca" },

        { label: "Togui", value: "Togui" },
        { label: "Topaga", value: "Topaga" },
        { label: "Tota", value: "Tota" },
        { label: "Tunungua", value: "Tunungua" },
        { label: "Turmeque", value: "Turmeque" },
        { label: "Tuta", value: "Tuta" },
        { label: "Tuzana", value: "Tuzana" },
        { label: "Umbita", value: "Umbita" },
        { label: "Ventaquemada", value: "Ventaquemada" },
        { label: "Villa de Leyva", value: "Villa de Leyva" },
        { label: "Viracha", value: "Viracha" },

        { label: "Zetaquira", value: "Zetaquira" },
      ];
      return Boyaca;
      break;

    case "Caldas":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Caldas = [
        { label: "Filadeflia", value: "Filadeflia" },
        { label: "La Merced", value: "La Merced" },
        { label: "Marmato", value: "Marmato" },
        { label: "Riosucio", value: "Riosucio" },
        { label: "Supia", value: "Supia" },

        { label: "Manzanares", value: "Manzanares" },
        { label: "Marquetalia", value: "Marquetalia" },
        { label: "Marulanda", value: "Marulanda" },
        { label: "Pensilvania", value: "Pensilvania" },
        { label: "Anserma", value: "Anserma" },
        { label: "Belalcazar", value: "Belalcazar" },
        { label: "Risaralda", value: "Risaralda" },
        { label: "San jose", value: "San jose" },
        { label: "Viterbo", value: "Viterbo" },
        { label: "Chinchina", value: "Chinchina" },
        { label: "Manizales", value: "Manizales" },

        { label: "Neira", value: "Neira" },

        { label: "Palestina", value: "Palestina" },
        { label: "Villamaria", value: "Villamaria" },
        { label: "La dorada", value: "La dorada" },
        { label: "Norcasia", value: "Norcasia" },
        { label: "Samana", value: "Samana" },
        { label: "Victoria", value: "Victoria" },
        { label: "Aguadas", value: "Aguadas" },
        { label: "Aranzazu", value: "Aranzazu" },
        { label: "Pacora", value: "Pacora" },
        { label: "Salamina", value: "Salamina" },
      ];
      return Caldas;
      break;

    case "Caqueta":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Caqueta = [
        { label: "Albania", value: "Albania" },
        { label: "Belen de los Andaquies", value: "Belen de los Andaquies" },
        { label: "Cartagena del Chaira", value: "Cartagena del Chaira" },
        { label: "Curillo", value: "Curillo" },
        { label: "El Doncello", value: "El Doncello" },
        { label: "El Paujil", value: "El Paujil" },
        { label: "Florencia", value: "Florencia" },
        { label: "La Montañita", value: "La Montañita" },
        { label: "Morelia", value: "Morelia" },
        { label: "Puerto Milan", value: "Puerto Milan" },
        { label: "Puerto Rico", value: "Puerto Rico" },
        { label: "San jose del Fragua", value: "San jose del Fragua" },
        { label: "San Vicente del Caguan", value: "San Vicente del Caguan" },
        { label: "Solano", value: "Solano" },
        { label: "Solita", value: "Solita" },
        { label: "Valparaiso", value: "Valparaiso" },
      ];
      return Caqueta;
      break;

    case "Casanare":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Casanare = [
        { label: "Aguazul", value: "Aguazul" },
        { label: "Chameza", value: "Chameza" },
        { label: "Hato Corozal", value: "Hato Corozal" },
        { label: "La Salina", value: "La Salina" },
        { label: "Mani", value: "Mani" },
        { label: "Monterrey", value: "Monterrey" },
        { label: "Nunchia", value: "Nunchia" },
        { label: "Orocue", value: "Orocue" },
        { label: "Paz de Ariporo", value: "Paz de Ariporo" },
        { label: "Pore", value: "Pore" },
        { label: "Recetor", value: "Recetor" },
        { label: "Sabanalarga", value: "Sabanalarga" },
        { label: "Sacama", value: "Sacama" },
        { label: "San luis de palenque", value: "San luis de palenque" },
        { label: "Tamara", value: "Tamara" },
        { label: "Trnidad", value: "Trnidad" },
        { label: "Villanueva", value: "Villanueva" },
        { label: "Yopal", value: "Yopal" },
      ];
      return Casanare;
      break;

    case "Cauca":
      //Declaraciones ejecutadas cuando el resultado de expresión coincide con valorN
      const Cauca = [
        { label: "Buenos Aires", value: "Buenos Aires" },
        { label: "Caloto", value: "Caloto" },
        { label: "Corinto", value: "Corinto" },
        { label: "Guachene", value: "Guachene" },
        { label: "Miranda", value: "Miranda" },
        { label: "Padilla", value: "Padilla" },
        { label: "Puerto Tejada", value: "Puerto Tejada" },
        { label: "Santander de Quilichao", value: "Santander de Quilichao" },
        { label: "Suarez", value: "Suarez" },
        { label: "Villa Rica", value: "Villa Rica" },
        { label: "Cajibio", value: "Cajibio" },
        { label: "El Tambo", value: "El Tambo" },
        { label: "La Sierra", value: "La Sierra" },
        { label: "Morales", value: "Morales" },
        { label: "Piendamo", value: "Piendamo" },
        { label: "Popayan", value: "Popayan" },
        { label: "Rosas", value: "Rosas" },
        { label: "Sotara", value: "Sotara" },
        { label: "Timbio", value: "Timbio" },
        { label: "Almaguer", value: "Almaguer" },
        { label: "Argelia", value: "Argelia" },
        { label: "Balboa", value: "Balboa" },
        { label: "Bolivar", value: "Bolivar" },
        { label: "Florencia", value: "Florencia" },
        { label: "La vega", value: "La vega" },
        { label: "Mercaderes", value: "Mercaderes" },
        { label: "Patia", value: "Patia" },
        { label: "Piamonte", value: "Piamonte" },
        { label: "San Sebastian", value: "San Sebastian" },
        { label: "Santa rosa", value: "Santa rosa" },
        { label: "Sucre", value: "Sucre" },
        { label: "Guapi", value: "Guapi" },
        { label: "Lopez de Micay", value: "Lopez de Micay" },
        { label: "Timbiqui", value: "Timbiqui" },
        { label: "Caldono", value: "Caldono" },
        { label: "Inza", value: "Inza" },
        { label: "Jambalo", value: "Jambalo" },
        { label: "Paez", value: "Paez" },
        { label: "Purace-Coconuco", value: "Purace-Coconuco" },
        { label: "Silvia", value: "Silvia" },
        { label: "Toribio", value: "Toribio" },
        { label: "Toro", value: "Toro" },
      ];
      return Cauca;

      break;
    case "Cesar":
      const Cesar = [
        { label: "Valledupar", value: "Valledupar" },
        { label: "Aguachica", value: "Aguachica" },
        { label: "Agustin Codazzi", value: "Agustin Codazzi" },
        { label: "Bosconia", value: "Bosconia" },
        { label: "Chimichagua", value: "Chimichagua" },
        { label: "El Copey", value: "El Copey" },
        { label: "San Alberto", value: "San Alberto" },
        { label: "Curumani", value: "Curumani" },
        { label: "El Paso", value: "El Paso" },
        { label: "La paz", value: "La paz" },
        { label: "Pueblo Bello", value: "Pueblo Bello" },

        { label: "La Jagua de Ibirio", value: "La Jagua de Ibirio" },
        { label: "Chiriguana", value: "Chiriguana" },
        { label: "Astrea", value: "Astrea" },
        { label: "San Martin", value: "San Martin" },
        { label: "Paleya", value: "Paleya" },
        { label: "Pailitas", value: "Pailitas" },
        { label: "Gamara", value: "Gamara" },
        {
          label: "Manaure Balcon del Cesar",
          value: "Manaure Balcon del Cesar",
        },
        { label: "Rio de Oro", value: "Rio de Oro" },
        { label: "Tamalameque", value: "Tamalameque" },
        { label: "Becerril", value: "Becerril" },

        { label: "San Diego", value: "San Diego" },
        { label: "La Gloria", value: "La Gloria" },
        { label: "Gonzales", value: "Gonzales" },
      ];
      return Cesar;
      break;

    case "Choco":
      const Choco = [
        { label: "Acandi", value: "Acandi" },
        { label: "Alto Baudo", value: "Alto Baudo" },
        { label: "Atrato", value: "Atrato" },
        { label: "Bagado", value: "Bagado" },
        { label: "Bahia Solano", value: "Bahia Solano" },
        { label: "Bajo Baudo", value: "Bajo Baudo" },
        { label: "Bojaya", value: "Bojaya" },
        { label: "Certegui", value: "Certegui" },
        { label: "Condoto", value: "Condoto" },
        { label: "El Canton de San Pablo", value: "El Canton de San Pablo" },
        { label: "El Carmen de Atrato", value: "El Carmen de Atrato" },

        { label: "El Carmen del Darien", value: "El Carmen del Darien" },
        { label: "El litoral de San juan", value: "El litoral de San juan" },
        { label: "Istmina", value: "Istmina" },
        { label: "Jurado", value: "Jurado" },
        { label: "Lloro", value: "Lloro" },
        { label: "PaiMedio Atratolitas", value: "PaiMedio Atratolita" },
        { label: "Medio Baudo", value: "Medio Baudo" },
        { label: "Medio San Juan", value: "Medio San Juan" },
        { label: "Novita", value: "Novita" },
        { label: "Nuqui", value: "Nuqui" },
        { label: "Quibdo", value: "Quibdo" },

        { label: "Rio Iro", value: "Rio Iro" },
        { label: "Rio o", value: "Rio o" },
        { label: "Riosucion", value: "Riosucion" },

        { label: "San jode del Palmar", value: "San jode del Palmar" },
        { label: "Sipi", value: "Sipi" },
        { label: "Tado", value: "Tado" },

        { label: "Unguia", value: "Unguia" },
        { label: "Union Panamerica", value: "Union Panamerica" },
      ];
      return Choco;
      break;

    case "Cordoba":
      const Cordoba = [
        { label: "Ayapel", value: "Ayapel" },
        { label: "Buenavista", value: "Buenavista" },
        { label: "Canalete", value: "Canalete" },
        { label: "Cerete", value: "Cerete" },
        { label: "Chima", value: "Chima" },
        { label: "Chinu", value: "Chinu" },
        { label: "Cienaga de Oro", value: "Cienaga de Oro" },
        { label: "Cotorra", value: "Cotorra" },
        { label: "La Apartada", value: "La Apartada" },
        { label: "Los Cordobas", value: "Los Cordobas" },
        { label: "Momil", value: "Momil" },

        { label: "Montelibano", value: "Montelibano" },
        { label: "Monteria", value: "Monteria" },
        { label: "Moñitos", value: "Moñitos" },
        { label: "Planeta Rica", value: "Planeta Rica" },
        { label: "Pueblo Nuevo", value: "Pueblo Nuevo" },
        { label: "Puerto Escondido", value: "Puerto Escondido" },
        { label: "Puerto Libertador", value: "Puerto Libertador" },
        { label: "Purisima", value: "Purisima" },
        { label: "Sahagun", value: "Sahagun" },
        { label: "San Andres de Sotovento", value: "San Andres de Sotovento" },
        { label: "San Antero", value: "San Antero" },

        { label: "San Bernardo del Viento", value: "San Bernardo del Viento" },
        { label: "San Carlos", value: "San Carlos" },
        { label: "San Jose de Ure", value: "San Jose de Ure" },

        { label: "San Pelayo", value: "San Pelayo" },
        { label: "Santa cruz de Lorixa", value: "Santa cruz de Lorixa" },
        { label: "Tierralta", value: "Tierralta" },

        { label: "Tuchin", value: "Tuchin" },
        { label: "Valencia", value: "Valencia" },
      ];
      return Cordoba;
      break;

    case "Cundinamarca":
      const Cundinamarca = [
        { label: "Agua de dios", value: "Agua de dios" },
        { label: "Alban", value: "Alban" },
        { label: "Analoima", value: "Analoima" },
        { label: "Apulo", value: "Apulo" },
        { label: "Arbelaez", value: "Arbelaez" },
        { label: "Beltran", value: "Beltran" },
        { label: "Bituima", value: "Bituima" },
        { label: "Bojaca", value: "Bojaca" },
        { label: "Cabrera", value: "Cabrera" },
        { label: "Cachipay", value: "Cachipay" },
        { label: "Cajica", value: "Cajica" },
        { label: "Caparrapi", value: "Caparrapi" },
        { label: "Caqueza", value: "Caqueza" },

        { label: "Carmen de Carupa", value: "Carmen de Carupa" },
        { label: "Chaguani", value: "Chaguani" },
        { label: "Chipaque", value: "Chipaque" },
        { label: "Choachi", value: "Choachi" },
        { label: "Choconta", value: "Choconta" },
        { label: "Cogua", value: "Cogua" },
        { label: "Cota", value: "Cota" },
        { label: "Cucunuba", value: "Cucunuba" },
        { label: "El colegio", value: "El colegio" },
        { label: "El peñol", value: "El peñol" },
        { label: "El rosal", value: "El rosa" },
        { label: "Fomeque", value: "Fomeque" },
        { label: "Fosca", value: "Fosca" },

        { label: "Fuquene", value: "Fuquene" },
        { label: "Gachancipa", value: "Gachancipa" },
        { label: "Gacheta", value: "Gacheta" },
        { label: "Gama", value: "Gama" },
        { label: "Granada", value: "Granada" },
        { label: "Guacheta", value: "Guacheta" },
        { label: "Guaduas", value: "Guaduas" },
        { label: "Guasca", value: "Guasca" },
        { label: "Guataqui", value: "Guataqui" },
        { label: "Guatabita", value: "Guatabita" },
        { label: "Guayabal de Siquima", value: "Guayabal de Siquima" },
        { label: "Guayabetal", value: "Guayabetal" },
        { label: "Gutierrez", value: "Gutierrez" },

        { label: "Jerusalen", value: "Jerusalen" },
        { label: "Junin", value: "Junin" },
        { label: "La calera", value: "La calera" },
        { label: "La mesa", value: "La mesa" },
        { label: "La palma", value: "La palma" },
        { label: "La peña", value: "La peña" },
        { label: "La vega", value: "La vega" },
        { label: "Laguazaque", value: "Laguazaque" },
        { label: "Macheta", value: "Macheta" },
        { label: "Madrid", value: "Madrid" },
        { label: "Manta", value: "Manta" },
        { label: "Medina", value: "Medina" },
        { label: "Mosquera", value: "Mosquera" },

        { label: "Nariño", value: "Nariño" },
        { label: "Nemocon", value: "Nemocon" },
        { label: "Nilo", value: "Nilo" },
        { label: "Nimaima", value: "Nimaima" },
        { label: "Nocaima", value: "Nocaima" },
        { label: "Pacho", value: "Pacho" },
        { label: "Paime", value: "Paime" },
        { label: "Pandi", value: "Pandi" },
        { label: "Paratebueno", value: "Paratebueno" },
        { label: "Pasca", value: "Pasca" },
        { label: "Puerto Salgar", value: "Puerto Salgar" },
        { label: "Puli", value: "Puli" },
        { label: "Quebradanegra", value: "Quebradanegra" },

        { label: "Quetame", value: "Quetame" },
        { label: "Quipile", value: "Quipile" },
        { label: "Ricaurte", value: "Ricaurte" },
        {
          label: "San Antonio de Tequendaman",
          value: "San Antonio de Tequendaman",
        },
        { label: "San bernardo", value: "San bernardo" },
        { label: "San cayetano", value: "San cayetano" },
        { label: "San francisco de sales", value: "San francisco de sales" },
        { label: "San juan de rioseco", value: "San juan de rioseco" },
        { label: "Sasaima", value: "Sasaima" },
        { label: "Sesquile", value: "Sesquile" },
        { label: "Silvania", value: "Silvania" },
        { label: "Simijaca", value: "Simijaca" },
        { label: "Sopo", value: "Sopo" },

        { label: "Subachoque", value: "Subachoque" },
        { label: "Suesca", value: "Suesca" },
        { label: "Sesquile", value: "Sesquile" },
        { label: "Silvania", value: "Silvania" },
        { label: "Simijaca", value: "Simijaca" },
        { label: "Sopo", value: "Sopo" },
        { label: "Subachoque", value: "Subachoque" },
        { label: "Suesca", value: "Suesca" },
        { label: "Supata", value: "Supata" },
        { label: "Susa", value: "Susa" },
        { label: "Sutatausa", value: "Sutatausa" },
        { label: "Tabio", value: "Tabio" },
        { label: "Tausa", value: "Tausa" },

        { label: "Tena", value: "Tena" },
        { label: "Tenjo", value: "Tenjo" },
        { label: "Tibacuy", value: "Tibacuy" },
        { label: "Tibirita", value: "Tibirita" },
        { label: "Tocaima", value: "Tocaima" },
        { label: "Tocancipa", value: "Tocancipa" },
        { label: "Topaipi", value: "Topaipi" },
        { label: "Ubala", value: "Ubala" },
        { label: "Ubaque", value: "Ubaque" },
        { label: "Ubate", value: "Ubate" },
        { label: "Une", value: "Une" },
        { label: "Utica", value: "Utica" },
        { label: "Venecia", value: "Venecia" },

        { label: "Vergara", value: "Vergara" },
        { label: "Viani", value: "Viani" },
        { label: "Villagomez", value: "Villagomez" },
        { label: "VillaPinzon", value: "VillaPinzon" },
        { label: "Villeta", value: "Villeta" },
        { label: "Viota", value: "Viota" },
        { label: "Yacopi", value: "Yacopi" },
        { label: "Zipacon", value: "Zipacon" },
        { label: "Zipaquira", value: "Zipaquira" },
      ];

      return Cundinamarca;
      break;

    case "Guainia":
      const Guainia = [
        { label: "Barrancominas", value: "Barrancominas" },
        { label: "Cacahual", value: "Cacahual" },
        { label: "Inirida", value: "Inirida" },
        { label: "La guadalupe", value: "La guadalupe" },
        { label: "Morichal nuevo", value: "Morichal nuevo" },
        { label: "Pana pana", value: "Pana pana" },
        { label: "Puerto Colombia", value: "Puerto Colombia" },
        { label: "San Felipe", value: "San Felipe" },
      ];

      return Guainia;
      break;

    case "Guaviare":
      const Guaviare = [
        { label: "Calamar", value: "Calamar" },
        { label: "El retorno", value: "El retorno" },
        { label: "Miraflores", value: "Miraflores" },
        { label: "San jose del guaviare", value: "San jose del guaviare" },
      ];

      return Guaviare;
      break;
    case "Huila":
      const Huila = [
        { label: "Aipe", value: "Aipe" },
        { label: "Algeciras", value: "Algeciras" },
        { label: "Inirida", value: "Inirida" },
        { label: "Baraya", value: "Baraya" },
        { label: "Campoalegre", value: "Campoalegre" },
        { label: "Colombia", value: "Colombia" },
        { label: "Hobo", value: "Hobo" },
        { label: "Iquira", value: "Iquira" },
        { label: "Neiva", value: "Neiva" },
        { label: "Palermo", value: "Palermo" },
        { label: "Rivera", value: "Rivera" },
        { label: "Santa Maria", value: "Santa Maria" },
        { label: "Pana pana", value: "Pana pana" },
        { label: "Tello", value: "Tello" },
        { label: "Teruel", value: "Teruel" },
        { label: "Villavieja", value: "Villavieja" },
        { label: "Yaguara", value: "Yaguara" },
        { label: "Agrado", value: "Agrado" },
        { label: "Alatamira", value: "Alatamira" },
        { label: "Garzon", value: "Garzon" },
        { label: "Gigante", value: "Gigante" },
        { label: "Guadalupe", value: "Guadalupe" },
        { label: "Pital", value: "Pital" },
        { label: "Suaza", value: "Suaza" },
        { label: "Tarqui", value: "Tarqui" },
        { label: "La Argentina", value: "La Argentina" },
        { label: "La plata", value: "La plata" },
        { label: "Nataga", value: "Nataga" },
        { label: "Paicol", value: "Paicol" },
        { label: "Tesalia", value: "Tesalia" },
        { label: "Acevedo", value: "Acevedo" },
        { label: "Elias", value: "Elias" },
        { label: "Isnos", value: "Isnos" },
        { label: "Pitalito", value: "Pitalito" },
        { label: "San Agustin", value: "San Agustin" },
        { label: "Timana", value: "Timana" },
      ];

      return Huila;
      break;

    case "La Guajira":
      const LaGuajira = [
        { label: "Albania", value: "Albania" },
        { label: "Barranca", value: "Barranca" },
        { label: "Dibulla", value: "Dibulla" },
        { label: "Distraccion", value: "Distraccion" },
        { label: "El Molino", value: "El Molino" },
        { label: "Fonseca", value: "Fonseca" },
        { label: "Hatonuevo", value: "Hatonuevo" },
        { label: "La Jagua del pilar", value: "La Jagua del pilar" },
        { label: "Maicao", value: "Maicao" },
        { label: "Manaure", value: "Manaure" },
        { label: "Riohacha", value: "Riohacha" },
        { label: "San juan del cesar", value: "San juan del cesar" },
        { label: "Uribia", value: "Uribia" },
        { label: "Urumita", value: "Urumita" },
        { label: "Villanueva", value: "Villanueva" },
      ];

      return LaGuajira;
      break;

    case "Magdalena":
      const Magdalena = [
        { label: "Algarrobo", value: "Algarrobo" },
        { label: "Aracataca", value: "Aracataca" },
        { label: "Ariguani", value: "Ariguani" },
        { label: "Cerro de san Antonio", value: "Cerro de san Antonio" },
        { label: "Chibolo", value: "Chibolo" },
        { label: "Cienaga", value: "Cienaga" },
        { label: "Concordia", value: "Concordia" },
        { label: "El Banco", value: "El Banco" },
        { label: "El Piñon", value: "El Piñon" },
        { label: "El reten", value: "El reten" },
        { label: "Fundacion", value: "Fundacion" },
        { label: "Guacamal", value: "Guacamal" },
        { label: "Nueva Granada", value: "Nueva Granada" },
        { label: "Pedraza", value: "Pedraza" },
        { label: "Pijiño del carmen", value: "Pijiño del carmen" },
        { label: "Pavijay", value: "Pavijay" },
        { label: "Plato", value: "Plato" },
        { label: "Pueblo Viejo", value: "Pueblo Viejo" },
        { label: "Remolino", value: "Remolino" },
        { label: "Sabana de san angel", value: "Sabana de san angel" },
        { label: "Salamina", value: "Salamina" },
        {
          label: "San sebastian de buena Vista",
          value: "San sebastian de buena Vista",
        },
        { label: "Santa Analoima", value: "Santa Analoima" },
        { label: "Santa Barbara de pinto", value: "Santa Barbara de pinto" },
        { label: "Santa marta", value: "Santa marta" },
        { label: "san Zenon", value: "san Zenon" },
        { label: "Sitio nuevo", value: "Sitio nuevo" },
        { label: "Tenerife", value: "Tenerife" },
        { label: "Zapayan", value: "Zapayan" },
        { label: "Zona sabanera", value: "Zona sabanera" },
        { label: "Albania", value: "Albania" },
      ];

      return Magdalena;
      break;

    case "Meta":
      const Meta = [
        { label: "Acacias", value: "Acacias" },
        { label: "Burranca de Upia", value: "Burranca de Upia" },
        { label: "Cabuyaro", value: "Cabuyaro" },
        { label: "Castilla la Nueva", value: "Castilla la Nueva" },
        { label: "Cubarral", value: "Cubarral" },
        { label: "Cumaral", value: "Cumaral" },
        { label: "El Calvario", value: "El Calvario" },
        { label: "El Castillo", value: "El Castillo" },
        { label: "El Dorado", value: "El Dorado" },
        { label: "Fuente de oro", value: "Fuente de oro" },
        { label: "Granada", value: "Granada" },
        { label: "Guacamal", value: "Guacamal" },
        { label: "La macarena", value: "La macarena" },
        { label: "La uribe", value: "La uribe" },
        { label: "Lejanias", value: "Lejanias" },
        { label: "Mapiripan", value: "Mapiripan" },
        { label: "Mesetas", value: "Mesetas" },
        { label: "Puerto concordia", value: "Puerto concordia" },
        { label: "Puerto gaitan", value: "Puerto gaitan" },
        { label: "Puerto Lleras", value: "Puerto Lleras" },
        { label: "Puerto Lopez", value: "Puerto Lopez" },
        { label: "Puerto rico", value: "Puerto rico" },
        { label: "Restrepo", value: "Restrepo" },
        { label: "San carlos de Guaroa", value: "San carlos de Guaroa" },
        { label: "San juan de arama", value: "San juan de arama" },
        { label: "San juanito", value: "San juanito" },
        { label: "San Martin", value: "San Martin" },
        { label: "Villavicencion", value: "Villavicencion" },
        { label: "Vista Hermosa", value: "Vista Hermosa" },
      ];
      return Meta;
      break;
    case "Nariño":
      const Narinio = [
        { label: "Barbacoas", value: "Barbacoas" },
        { label: "El charco", value: "El charco" },
        { label: "Francisco Pizarro", value: "Francisco Pizarro" },
        { label: "La tola", value: "La tola" },
        { label: "Magui payan", value: "Magui payan" },
        { label: "Mosquera", value: "Mosquera" },
        { label: "Olaya Herrera", value: "Olaya Herrera" },
        { label: "Roberto Popayan", value: "Roberto Popayan" },
        { label: "Santa Barbara", value: "Santa Barbara" },
        { label: "Tumaco", value: "Tumaco" },
        { label: "Aldana", value: "Aldana" },
        { label: "Contadero", value: "Contadero" },
        { label: "Cordoba", value: "Cordoba" },
        { label: "Causpud", value: "Causpud" },
        { label: "Cumbal", value: "Cumbal" },
        { label: "Funes", value: "Funes" },
        { label: "Guachucal", value: "Guachucal" },
        { label: "Gualmatan", value: "Gualmatan" },
        { label: "Iles", value: "Iles" },
        { label: "Ipiales", value: "Ipiales" },
        { label: "Potosi", value: "Potosi" },
        { label: "Puerres", value: "Puerres" },
        { label: "Pupiales", value: "Pupiales" },
        { label: "Alban", value: "Alban" },
        { label: "Arboleda", value: "Arboleda" },
        { label: "Belen", value: "Belen" },
        { label: "Colon", value: "Colon" },
        { label: "El rosario", value: "El rosario" },
        { label: "El tablon de Gomez", value: "El tablon de Gomez" },

        { label: "La cruz", value: "La cruz" },
        { label: "La union", value: "La union" },
        { label: "Leiva", value: "Leiva" },
        { label: "Policarpa", value: "Policarpa" },
        { label: "San bernardo", value: "San bernardo" },
        { label: "San Lorenzo", value: "San Lorenzo" },
        { label: "San pablo", value: "San pablo" },
        { label: "San pedro de cartago", value: "San pedro de cartago" },
        { label: "Timinango", value: "Timinango" },
        { label: "Buesaco", value: "Buesaco" },
        { label: "Chachagui", value: "Chachagui" },
        { label: "consaca", value: "consaca" },
        { label: "El peñol", value: "El peñol" },
        { label: "El tambo", value: "El tambo" },
        { label: "La florida", value: "La florida" },
        { label: "Nariño", value: "Nariño" },
        { label: "Pasto", value: "Pasto" },
        { label: "Sandona", value: "Sandona" },
        { label: "Tagua", value: "Tagua" },
        { label: "Yacuenquer", value: "Yacuenquer" },

        { label: "Ancuya", value: "Ancuya" },
        { label: "Cumbitara", value: "Cumbitara" },
        { label: "Guatarilla", value: "Guatarilla" },
        { label: "Imues", value: "Imues" },
        { label: "La llanada", value: "La llanada" },
        { label: "Linares", value: "Linares" },
        { label: "Los Andes", value: "Los Andes" },
        { label: "Mallama", value: "Mallama" },
        { label: "Ospina", value: "Ospina" },
        { label: "Provicendia", value: "Provicendia" },
        { label: "Ricaurte", value: "Ricaurte" },
        { label: "Samaniego", value: "Samaniego" },
        { label: "Santa cruz", value: "Santa cruz" },
        { label: "Sapuyes", value: "Sapuyes" },
        { label: "Tuquerrez", value: "Tuquerrez" },
      ];
      return Narinio;
      break;
    case "Norte de Santander":
      const NorteDeSantander = [
        { label: "Arboledas", value: "Arboledas" },
        { label: "Cucutilla", value: "Cucutilla" },
        { label: "Gramalote", value: "Gramalote" },
        { label: "Loures", value: "Loures" },
        { label: "Salazar de las palmas", value: "Salazar de las palmas" },
        { label: "Santiago", value: "Santiago" },
        { label: "Villa caro", value: "Villa caro" },
        { label: "Cucuta", value: "Cucuta" },
        { label: "El zulia", value: "El zulia" },
        { label: "Los patios", value: "Los patios" },
        { label: "Puerto Santander", value: "Puerto Santander" },
        { label: "San cayetano", value: "San cayetano" },
        { label: "Villa del rosario", value: "Villa del rosario" },
        { label: "Bucarasica", value: "Bucarasica" },
        { label: "El tarra", value: "El tarra" },
        { label: "Sardinata", value: "Sardinata" },
        { label: "Tibu", value: "Tibu" },
        { label: "Abrego", value: "Abrego" },
        { label: "Cachira", value: "Cachira" },
        { label: "Convencion", value: "Convencion" },

        { label: "El carmen", value: "El carmen" },
        { label: "Hacari", value: "Hacari" },
        { label: "La esperanza", value: "La esperanza" },
        { label: "La playa de belen", value: "La playa de belen" },
        { label: "Ocaña", value: "Ocaña" },
        { label: "San calixto", value: "San calixto" },
        { label: "Teorama", value: "Teorama" },
        { label: "Cacota", value: "Cacota" },
        { label: "Chitaga", value: "Chitaga" },
        { label: "Mutiscua", value: "Mutiscua" },
        { label: "Pamplona", value: "Pamplona" },
        { label: "Pamplonita", value: "Pamplonita" },
        { label: "Santo domingo de Silios", value: "Santo domingo de Silios" },
        { label: "Bochalema", value: "Bochalema" },
        { label: "Tuquerrez", value: "Tuquerrez" },

        { label: "Chinacota", value: "Chinacota" },
        { label: "Durania", value: "Durania" },
        { label: "Herran", value: "Herran" },

        { label: "Labateca", value: "Labateca" },
        { label: "Ragonvalia", value: "Ragonvalia" },
        { label: "Toledo", value: "Toledo" },
      ];
      return NorteDeSantander;
      break;
    case "Putumayo":
      const Putumayo = [
        { label: "Colon", value: "Colon" },
        { label: "Mocoa", value: "Mocoa" },
        { label: "Orito", value: "Orito" },
        { label: "Puerto Asis", value: "Puerto Asi" },
        { label: "Puerto Caicedo", value: "Puerto Caicedo" },
        { label: "Puerto Guzman", value: "Puerto Guzman" },
        { label: "Puerto Leguizamo", value: "Puerto Leguizamo" },

        { label: "San Francisco", value: "San Francisco" },
        { label: "San Miguel", value: "San Miguel" },
        { label: "Santiago", value: "Santiago" },

        { label: "Sibundoy", value: "Sibundoy" },
        { label: "Valle del Guamuez", value: "Valle del Guamuez" },
        { label: "Villagarzon", value: "Villagarzon" },
      ];
      return Putumayo;
      break;
    case "Quindio":
      const Quindio = [
        { label: "Armenia", value: "Armenia" },
        { label: "Buenavista", value: "Buenavista" },
        { label: "Calarca", value: "Calarca" },
        { label: "Circasia", value: "Circasia" },
        { label: "Cordoba", value: "Cordoba" },
        { label: "Filandia", value: "Filandia" },
        { label: "Genova", value: "Genova" },

        { label: "La tebaida", value: "La tebaida" },
        { label: "Montenegro", value: "Montenegro" },
        { label: "Pijao", value: "Pijao" },

        { label: "Quimbaya", value: "Quimbaya" },
        { label: "Salento", value: "Salento" },
      ];
      return Quindio;
      break;
    case "Risaralda":
      const Risaralda = [
        { label: "Apia", value: "Apia" },
        { label: "Balboa", value: "Balboa" },
        { label: "Belen de Umbria", value: "Belen de Umbria" },
        { label: "Dosquebradas", value: "Dosquebradas" },
        { label: "Guatica", value: "Guatica" },
        { label: "La celia", value: "La celia" },
        { label: "La virginia", value: "La virginia" },
        { label: "Marsella", value: "Marsella" },
        { label: "Mistrato", value: "Mistrato" },
        { label: "Pereira", value: "Pereira" },
        { label: "Pueblo rico", value: "Pueblo rico" },
        { label: "Quinchia", value: "Quinchia" },
        { label: "Santa rosa de cabal", value: "Santa rosa de cabal" },
        { label: "Santuario", value: "Santuario" },
      ];
      return Risaralda;
      break;

    case "Santander":
      const Santander = [
        { label: "Aguada", value: "Aguada" },
        { label: "Albania", value: "Albania" },
        { label: "Aratoca", value: "Aratoca" },
        { label: "Barbosa", value: "Barbosa" },
        { label: "Barichara", value: "Barichara" },
        { label: "Barrancabermeja", value: "Barrancabermeja" },
        { label: "Betulia", value: "Betulia" },
        { label: "Bolivar", value: "Bolivar" },
        { label: "Bucaramanga", value: "Bucaramanga" },
        { label: "Cabrera", value: "Cabrera" },
        { label: "California", value: "California" },
        { label: "Capitanejo", value: "Capitanejo" },
        { label: "Carcasi", value: "Carcasi" },
        { label: "Cepita", value: "Cepita" },
        { label: "Cerrito", value: "Cerrito" },
        { label: "Charala", value: "Charala" },
        { label: "Charta", value: "Charta" },
        { label: "Chima", value: "Chima" },
        { label: "Chipata", value: "Chipata" },
        { label: "Cimitarra", value: "Cimitarra" },
        { label: "Concepcion", value: "Concepcion" },
        { label: "Confines", value: "Confines" },
        { label: "Contratacion", value: "Contratacion" },
        { label: "Coromoro", value: "Coromoro" },
        { label: "Curiti", value: "Curiti" },
        { label: "El carmen de chucurri", value: "El carmen de chucurri" },
        { label: "El Guacamayo", value: "El Guacamayo" },
        { label: "El peñon", value: "El peñon" },
        { label: "El payon", value: "El payon" },
        { label: "Encino", value: "Encino" },
        { label: "Enciso", value: "Enciso" },
        { label: "Florian", value: "Florian" },
        { label: "Floridablanca", value: "Floridablanca" },
        { label: "Galan", value: "Galan" },
        { label: "Gambita", value: "Gambita" },
        { label: "Giron", value: "Giron" },
        { label: "Guaca", value: "Guaca" },
        { label: "Guadalupe", value: "Guadalupe" },
        { label: "Guapota", value: "Guapota" },
        { label: "Guavata", value: "Guavata" },
        { label: "Guepsa", value: "Guepsa" },
        { label: "Hato", value: "Hato" },
        { label: "Jesus Maria", value: "Jesus Maria" },
        { label: "Jordan", value: "Jordan" },
        { label: "La Belleza", value: "La Belleza" },
        { label: "La paz", value: "La paz" },
        { label: "Landazuri", value: "Landazuri" },
        { label: "Lebrija", value: "Lebrija" },
        { label: "Los Santos", value: "Los Santos" },
        { label: "Macaravita", value: "Macaravita" },
        { label: "Malaga", value: "Malaga" },
        { label: "Matanza", value: "Matanza" },
        { label: "Mogotes", value: "Mogotes" },
        { label: "Molagavita", value: "Molagavita" },
        { label: "Ocamonte", value: "Ocamonte" },
        { label: "Oiba", value: "Oiba" },
        { label: "Onzaga", value: "Onzaga" },
        { label: "Palmar", value: "Palmar" },
        { label: "Palmas de Socorro", value: "Palmas de Socorro" },
        { label: "Paramo", value: "Paramo" },
        { label: "Piedecuesta", value: "Piedecuesta" },
        { label: "Pinchote", value: "Pinchote" },
        { label: "Puente Nacional", value: "Puente Nacional" },
        { label: "Puero parra", value: "Puero parra" },
        { label: "Puerto wilches", value: "Puerto wilches" },
        { label: "Rionegro", value: "Rionegro" },
        { label: "Sabana de torres", value: "Sabana de torres" },
        { label: "San Andres", value: "San Andres" },
        { label: "San Benito", value: "San Benito" },
        { label: "San Gil", value: "San Gil" },
        { label: "San joaquin", value: "San joaquin" },
        { label: "San jose de miranda", value: "San jose de miranda" },
        { label: "San Miguel", value: "San Miguel" },
        { label: "San vicente de chucuri", value: "San vicente de chucuri" },
        { label: "Santa Barbara", value: "Santa Barbara" },
        { label: "Santa Elena del Opon", value: "Santa Elena del Opon" },

        { label: "Simacotata", value: "Simacotata" },
        { label: "Socorro", value: "Socorro" },
        { label: "Suaita", value: "Suaita" },
        { label: "Sucre", value: "Sucre" },
        { label: "Surata", value: "Surata" },
        { label: "Tona", value: "Tona" },
        { label: "Valle de san jose", value: "Valle de san jose" },

        { label: "Velez", value: "Velez" },
        { label: "Vetas", value: "Vetas" },
        { label: "Villanueva", value: "Villanueva" },
        { label: "Zapatoca", value: "Zapatoca" },
      ];
      return Santander;
      break;
    case "Sucre":
      const sucre = [
        { label: "Guaranda", value: "Guaranda" },
        { label: "Sucre", value: "Sucre" },
        { label: "Chalan", value: "Chalan" },
        { label: "Coloso", value: "Coloso" },
        { label: "Morroa", value: "Morroa" },
        { label: "Ovejas", value: "Ovejas" },
        { label: "Sincelejo", value: "Sincelejo" },
        { label: "Coveñas", value: "Coveñas" },
        { label: "Palmitos", value: "Palmitos" },
        { label: "San Onofre", value: "San Onofre" },
        { label: "Santiago de Tolu", value: "Santiago de Tolu" },
        { label: "Toluviejo", value: "Toluviejo" },
        { label: "Buenvista", value: "Buenvista" },

        { label: "Corozal", value: "Corozal" },
        { label: "El roble", value: "El roble" },
        { label: "Galeras", value: "Galeras" },
        { label: "Los Palmitos", value: "Los Palmitos" },
        { label: "Sampues", value: "Sampues" },
        { label: "San juan de betulia", value: "San juan de betulia" },
        { label: "San Pedro", value: "San Pedro" },

        { label: "Since", value: "Since" },
        { label: "Caimo", value: "Caimo" },
        { label: "La union", value: "La union" },
        { label: "San benito Abad", value: "San benito Abad" },
        { label: "San Marcos", value: "San Marcos" },
      ];

      return sucre;
      break;

    case "Tolima":
      const Tolima = [
        { label: "Alvarado", value: "Alvarado" },
        { label: "Anzoategui", value: "Anzoategui" },
        { label: "Cajmarca", value: "Cajmarca" },
        { label: "Coello", value: "Coello" },
        { label: "Espinal", value: "Espinal" },
        { label: "Flandes", value: "Flandes" },
        { label: "Ibague", value: "Ibague" },
        { label: "Piedras", value: "Piedras" },
        { label: "Rovira", value: "Rovira" },
        { label: "San Luis", value: "San Luis" },
        { label: "Valle de San Juan", value: "Valle de San Juan" },
        { label: "Casabianca", value: "Casabianca" },
        { label: "Herveo", value: "Herveo" },
        { label: "Lerida", value: "Lerida" },
        { label: "Libano", value: "Libano" },
        { label: "Murillo", value: "Murillo" },
        { label: "Santa Isabel", value: "Santa Isabel" },

        { label: "Venadillo", value: "Venadillo" },
        { label: "Villahermosa", value: "Villahermosa" },
        { label: "Ambalema", value: "Ambalema" },
        { label: "Armero", value: "Armero" },
        { label: "Falan", value: "Falan" },
        { label: "Fresno", value: "Fresno" },
        { label: "Honda", value: "Honda" },

        {
          label: "San sebastina de mariquita",
          value: "San sebastina de mariquita",
        },
        { label: "Polocabildo", value: "Polocabildo" },
        { label: "Carme de apicala", value: "Carme de apicala" },
        { label: "Cunday", value: "Cunday" },
        { label: "Icononzo", value: "Icononzo" },

        { label: "Melgar", value: "Melgar" },
        { label: "Villarica", value: "Villarica" },
        { label: "Ataco", value: "Ataco" },
        { label: "Chaparral", value: "Chaparral" },
        { label: "Coyaima", value: "Coyaima" },
        { label: "Natagima", value: "Natagima" },
        { label: "Ortega", value: "Ortega" },

        { label: "Planadas", value: "Planadas" },
        { label: "Rioblanco", value: "Rioblanco" },
        { label: "Roncesvalles", value: "Roncesvalles" },
        { label: "San Antonio", value: "San Antonio" },
        { label: "Alpujarra", value: "Alpujarra" },

        { label: "Dolores", value: "Dolores" },
        { label: "Guamo", value: "Guamo" },
        { label: "Prado", value: "Prado" },
        { label: "Purificacion", value: "Purificacion" },
        { label: "Saldaña", value: "Saldaña" },
        { label: "Suarez", value: "Suarez" },
      ];
      return Tolima;

    case "Valle del Cauca":
      const ValleDelCauca = [
        { label: "Alcala", value: "Alcala" },
        { label: "Andalucia", value: "Andalucia" },
        { label: "Ansermanuevo", value: "Ansermanuevo" },
        { label: "Argelia", value: "Argelia" },
        { label: "Bolivar", value: "Bolivar" },
        { label: "Buenaventura", value: "Buenaventura" },
        { label: "Buga", value: "Buga" },
        { label: "Bugalagrande", value: "Bugalagrande" },
        { label: "Caicedonia", value: "Caicedonia" },
        { label: "Cali", value: "Cali" },
        { label: "Calima -El Darien", value: "Calima -El Darien" },
        { label: "Candelaria", value: "Candelaria" },
        { label: "Cartago", value: "Cartago" },
        { label: "Dagua", value: "Dagua" },
        { label: "El Aguila", value: "El Aguila" },
        { label: "El Cairo", value: "El Cairo" },
        { label: "El Cerrito", value: "El Cerrito" },

        { label: "El dovio", value: "El dovio" },
        { label: "Florida", value: "Florida" },
        { label: "Ginebra", value: "Ginebra" },
        { label: "Guacari", value: "Guacari" },
        { label: "Jamaundi", value: "Jamaundi" },
        { label: "La cumbre", value: "La cumbre" },
        { label: "La union", value: "La union" },

        { label: "La victoria", value: "La victoria" },
        { label: "Obando", value: "Obando" },
        { label: "Palmira", value: "Palmira" },
        { label: "Pradera", value: "Pradera" },
        { label: "Restrepo", value: "Restrepo" },

        { label: "Riofrio", value: "Riofrio" },
        { label: "Roldanillo", value: "Roldanillo" },
        { label: "San pedro", value: "San pedro" },
        { label: "Sevilla", value: "Sevilla" },
        { label: "Toro", value: "Toro" },
        { label: "Trujillo", value: "Trujillo" },
        { label: "Tulua", value: "Tulua" },

        { label: "Ulloa", value: "Ulloa" },
        { label: "Versalles", value: "Versalles" },
        { label: "Vijes", value: "Vijes" },
        { label: "Yocoto", value: "Yocoto" },
        { label: "Yumbo", value: "Yumbo" },

        { label: "Zarzal", value: "Zarzal" },
      ];
      return ValleDelCauca;
      break;

    case "Vaupes":
      const Vaupes = [
        { label: "Caruru", value: "Caruru" },
        { label: "Mitu", value: "Mitu" },
        { label: "Pacoa", value: "Pacoa" },
        { label: "Papunaua", value: "Papunaua" },
        { label: "Taira", value: "Taira" },

        { label: "Yavarate", value: "Yavarate" },
      ];
      return Vaupes;
      break;

    case "Vichada":
      const Vichada = [
        { label: "Cumaribo", value: "Cumaribo" },
        { label: "La primavera", value: "La primavera" },
        { label: "Puerto Carreño", value: "Puerto Carreño" },
        { label: "Santa rosalia", value: "Santa rosalia" },
      ];
      return Vichada;
      break;

    case "San Andres y Providencia":
      const SanAndresyProvidencia = [
        { label: "San Andres", value: "San Andres" },
        { label: "Providencia", value: "Providencia" },
        { label: "Santa Catalina", value: "Santa Catalina" },
        { label: "Cayos", value: "Cayos" },
      ];
      return SanAndresyProvidencia;
      break;

    default:
      //Declaraciones ejecutadas cuando ninguno de los valores coincide con el valor de la expresión
      break;
  }
}
